[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "windsurf-patient-dashboard"
version = "1.0.0"
description = "A Flask-based patient dashboard application"
requires-python = ">=3.11" 